### ISSUE TITLE
Hiding/removing controls

### ISSUE THREAD

**Issue by basharovV** [clearlysid/tauri-plugin-decorum#28]
Hi, thanks for this library! I was looking to have more control over the window buttons without affecting window borders and shadows. 

Is it possible to remove/hide the buttons programmatically? For my use-case: I want to be able to hide them in the mini-player.

**Comment by clearlysid** [comment]
Hey @basharovV I think you can just use some CSS to hide the window buttons (on Windows)...
```css
div[data-tauri-decorum-tb] {
   display: none;
}
```
